### ISSUE TITLE
alglib.rmatrixevd cound support double[,,]?

### ISSUE THREAD

**Issue by LetGo** [griffo-io/alglib.net.gpl#1]
alglib.rmatrixevd cound support double[,,] 3d? 

    public static void rmatrixhessenberg(ref double[ , , ] a,
            int n,
            ref double[,] tau,
            alglib.xparams _params)

**Comment by dariogriffo** [comment]
Hi, this is a public mirror for https://www.alglib.net/
since they don't genearte nuget packages I do, but I'm not maintaner of alglib.net
